### ISSUE TITLE
CLRProfilingAnalyzer - Identify if the below exception is fatal or not and if it can be fixed

### ISSUE THREAD

**Issue by puneetg1983** [ShekharGupta1988/AppLensV2#1036]
`System.IO.DirectoryNotFoundException : Could not find a part of the path 'D:\local\Temp\Reports\<REMOVING SITE NAME>\18-03-05\180305_1207268897\CLRProfilingAnalyzer\RD0003FF44E26F\reportdata\requests.json'. 
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at ClrProfilingAnalyzer.Program.DumpSlowRequests(Dictionary`2 iisRequests, ClrProfilingAnalyzerStats stats)
   at ClrProfilingAnalyzer.Program.Main(String[] args)
`

**Comment by puneetg1983** [comment]
Researched on it a bit and found that this is happening when an customer is choosing both "CLR Profiler" and "CLR Profiler with Thread Stacks" option. This is not possible in supportportalv2 so they are doing this possibly in the Support Portal or directly browsing to /DAAS. 

Have a fix in mind for this from the back end side but we should just get rid of the Support Portal UI in the mean time.
