### ISSUE TITLE
PROD : Check for Invalid Date Time

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#105]
System.Exception: Invalid Start Time and End Time. Start Time is after End Time.
   at Microsoft.Web.Hosting.Diagnostics.Common.DiagnosticUtilities.PrepareStartEndTimeUtc(String startTime, String endTime, DateTime& startTimeUtc, DateTime& endTimeUtc)
   at Microsoft.Web.Hosting.Diagnostics.Common.DiagnosticUtilities.PrepareStartEndTimeWithTimeGrain(String startTime, String endTime, String timeGrain, DateTime& startTimeUtc, DateTime& endTimeUtc, TimeSpan& timeGrainTimeSpan)
   at DiagnosticRole.Controllers.SitesController.<GetApplicationAnalysis>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

What actually happened here is that they gave a start time that was after the current time.

**Comment by PraveenTB** [comment]
Yes - now that ICM alerts are enabled, coz alerts start firing for all 5xx
