### ISSUE TITLE
PROD : Kusto Query execution failures - task cancelled -  AdalServiceException

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#176]
https://wawscus.kusto.windows.net:443/wawsprod [Run in Kusto.Explorer] [Run in Kusto.WebExplorer] 
DiagnosticRole | where RequestId == "g-9b3a7d4d-e279-42c0-9e0a-35fc05057d80" 
DiagnosticRole | where RequestId in ("g-468b85ba-dda4-4284-b3b9-74441dc641f2", "g-65492711-d64e-4322-be74-794cd35a8417", "g-d181b33a-251d-430c-a7d9-919b7b138271", "g-4256220e-0e07-4cd0-9e59-5efcffbd3ac0", "g-6348b3a0-ca4c-484a-98ec-4ea68b653f94")

All the errors came from one site:
DiagnosticRole | where SiteName == "d1aas-publicui-prod" 

Error:
System.Exception: Failed to Execute Kusto Query. Kusto ClientRequestId : c5179f3f-b861-4919-95c2-d529be67b449, Exception : Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: unknown_error: Unknown error ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext()

**Comment by ShekharGupta1988** [comment]
More Requests:
g-dc329650-bc97-4c5f-a448-4ab008bd986c
g-91ae6b92-ffdc-4113-aa00-ca623271e87b
g-621b2685-f677-4751-aba1-c6b54ce865bd

**Comment by ShekharGupta1988** [comment]
no repro. Didnt happened again
