### ISSUE TITLE
PROD : SlotRuntimeSitenameMap failure

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#177]
https://wawscus.kusto.windows.net:443/wawsprod [Run in Kusto.Explorer] [Run in Kusto.WebExplorer] 
DiagnosticRole | where RequestId == "g-0fa0a783-d558-4ad3-b1f1-cd8623e013e3"

Date: 2016-12-12 22:26:41 UTC

Error:
The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Diagnostics.Common.SlotRuntimeSitenameMapProvider.<GetObserverDataFromUrl>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Diagnostics.Common.SlotRuntimeSitenameMapProvider.<GetSlotRuntimeSitenameMap>d__0.MoveNext()

**Comment by ShekharGupta1988** [comment]
Two more requests failed:
g-961f0115-a124-4f5c-9603-c9f7756da712
g-28f1cbcc-f1da-4c6c-b96e-e2d666543109

**Comment by ShekharGupta1988** [comment]
RequestId
g-66e3a023-7c73-4ec8-b6b2-85bf4ae0baf2
g-828fc41b-daa7-4292-ae09-3a738d9a2cbb
g-6399ae2e-dfa6-4bbc-a177-f65c926e3d70
g-e2c9246d-0d24-44ea-8260-d13982511ce3
g-99754003-ea6b-48d2-a5af-35262b5c93ba
g-a41439e6-2463-4fcb-8b58-2911bba45352
g-704600bc-37de-437a-afa8-d5ffeb052c39
g-e0277d83-ccdd-4f46-afdf-3cb3cf286235
g-fc726a51-7c70-44f7-b0d9-e54c2123f095
g-3aa21b13-8a47-4c9d-ac12-1173a2e98e59
g-b10096e4-5dec-42e8-bb50-eea416f23cce
g-bee9ca1a-1371-4a00-9bef-1d437e52473b

**Comment by aspaan** [comment]
duplicate as login issue
