### ISSUE TITLE
Exceptions in detector base do not have correct stack trace

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#277]
Stack trace doesn't tell you the actual location of the exception

**Comment by stevenernst131** [comment]
**Before**:
Message: ArgumentException
StackTrace:    at Microsoft.Web.Hosting.Diagnostics.Common.DetectorBase.<DetectAsync>d__0.MoveNext()

**After**:
Message: ArgumentException
StackTrace:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerHighCPUDetector.CastToMetricSets(DataTable[] datatables, DataTable workerProcessDataTable, Dictionary`2 slotMap, Dictionary`2 workerMapping)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerHighCPUDetector.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DetectorBase.<DetectAsync>d__0.MoveNext()
