### ISSUE TITLE
Service Health Detector Exception

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#329]

**Comment by stevenernst131** [comment]
Message: ArgumentNullException
StackTrace:    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Web.Hosting.Diagnostics.Common.ServiceHealthDetector.<RunAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DetectorBase.<DetectAsync>d__0.MoveNext()
