### ISSUE TITLE
Intermittent Kusto Failures

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#338]
Couple of request Ids failed in PROD:
g-ff182e7f-817e-4477-a37f-4dcda4654725 
g-4fb0e4aa-0708-45b0-be3d-bdb09d6048ae 

Exception:
Message: Exception
StackTrace:    at Microsoft.Web.Hosting.Diagnostics.Common.KustoManager.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Diagnostics.Common.KustoDataProvider.<GetCanaryNameForSite>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DataSourceManager.<MakeDependencyCall>d__10`1.MoveNext()

**Comment by stevenernst131** [comment]
This doesn't seem like a problem that is only for GetCanaryNameForSite:

(cluster('wawseas').database('wawsprod').DiagnosticRole)
| union (cluster('wawseus').database('wawsprod').DiagnosticRole)
| union (cluster('wawsneu').database('wawsprod').DiagnosticRole)
| union (cluster('wawscus').database('wawsprod').DiagnosticRole)
| where TIMESTAMP > ago(7d)
| where ExceptionDetails contains "Microsoft.Web.Hosting.Diagnostics.Common.KustoManager.<ExecuteQueryAsync>d__0.MoveNext()"

Seems like an intermittent kusto issue?

**Comment by stevenernst131** [comment]
Shekhar, adding you because this seems like something that just happens with kusto sometimes, and as we have seen often times as a result of their deployment.

**Comment by ShekharGupta1988** [comment]
Closing this. When kusto rollout happens, right now, clients do experience intermittent connectivity issues.
There is no action item at our end for this.
