### ISSUE TITLE
GetSlotRuntimeSitenameMap PROD failures : Unable to connect to the remote server

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#339]
There were 3 requests that got this warning when trying to use RuntimeMap:

RequestId
g-868c7ea7-9681-49c8-aee0-df1002925819
g-81498ed4-50d1-4a1a-9180-df0aafddcf3d
g-890aab17-51e4-405c-a9f6-0f92121775bd

Unable to connect to the remote server
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Diagnostics.Common.SlotRuntimeSitenameMapProvider.<GetObserverDataFromUrl>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Diagnostics.Common.SlotRuntimeSitenameMapProvider.<GetSlotRuntimeSitenameMap>d__0.MoveNext()

**Comment by ShekharGupta1988** [comment]
(cluster('wawseas').database('wawsprod').DiagnosticRole)
| union (cluster('wawseus').database('wawsprod').DiagnosticRole)
| union (cluster('wawsneu').database('wawsprod').DiagnosticRole) | where TIMESTAMP >= datetime(2017-02-11 00:00)  and RequestId == "<Request Id>"

**Comment by aspaan** [comment]
Adding Retry and Request Id in slot map call
