### ISSUE TITLE
Nullref in cpu analysis/memory analysis

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#352]
Requests:
["g-3b020547-54c2-417e-9c65-c8c883d5190c","g-d451ca8f-efe1-47b2-ab97-4f7db6e0c485"]
["g-3b020547-54c2-417e-9c65-c8c883d5190c","g-d451ca8f-efe1-47b2-ab97-4f7db6e0c485"]

Message: NullReferenceException
StackTrace:    at Microsoft.Web.Hosting.Diagnostics.Common.WorkerHighMemoryDetector.FindAbnormalTimePeriods(DiagnosticMetricSets memoryMetricSets, List`1 workerMapping)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerHighMemoryDetector.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DetectorBase.<DetectAsync>d__0.MoveNext()

Message: NullReferenceException
StackTrace:    at Microsoft.Web.Hosting.Diagnostics.Common.WorkerHighCPUDetector.FindAbnormalTimePeriods(DiagnosticMetricSets cpuMetricSets, List`1 workerMapping)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerHighCPUDetector.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DetectorBase.<DetectAsync>d__0.MoveNext()

**Comment by stevenernst131** [comment]
This is fixed in msftintdm3, needs to be deployed everywhere else
