### ISSUE TITLE
Freb XmlException

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#383]
RequestIds:
g-773a885a-45f4-47b8-bec5-29ab44a04dc3, g-c4cdeafb-bc5f-41de-9c3c-e6c6e6ad58f8, 
g-d9c804a3-058c-40bf-8e3e-24a3904cb078

System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerFrebLogsDetector.ParseExceptionType(String rawValue)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerFrebLogsDetector.GetAppEventLogsData(DataTable workerEventLogsData)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerFrebLogsDetector.CastToMetricSets(DataTable frebLogsData, DataTable eventLogsData, List`1 slotTimeRangesForaSlot, List`1& abnormalPeriods, List`1 httpAbnormalTimePeriods)
   at Microsoft.Web.Hosting.Diagnostics.Common.WorkerFrebLogsDetector.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DetectorBase.<DetectAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DiagnosticRole.Controllers.SitesController.<GetDetectorResource>d__1f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

**Comment by stevenernst131** [comment]
I have upgraded this to PROD because we should not take the build that is in MSFTINTDM3 to other prod endpoints until Andrey has a fix
