### ISSUE TITLE
gm-prod-sn1 tenant issue

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#661]
System.Exception: Tenant Id List cannot be null or empty for stamp : waws-prod-blu-aef451c5
   at Microsoft.Web.Hosting.Diagnostics.Common.KustoDataProvider.<GetKustoQueryWithMetaData>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Diagnostics.Common.DataSourceManager.<GetDataTaskAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DetectorDataSource.<GetDataTaskAsync>d__0`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.RuntimeAvailabilityDetector.<RunAsync>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.DetectorBase.<DetectAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Diagnostics.Common.SiaAnalysis.<RunAsync>d__e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DiagnosticRole.Controllers.SitesController.<GetApplicationAnalysisEnvelope>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

**Comment by andreyse** [comment]
RequestId for this : ["g-b5f92ec1-35a6-480f-9a3f-9802f67055f4"] for the stack trace above 

Search for the last 7 days on MSFTINTDM3

**Comment by andreyse** [comment]
https://wawscus.kusto.windows.net:443/wawsprod?query=H4sIAAAAAAAEAHXOsQ6CMBSF4d3Ed7hhgqHmtqWUEnVycTPoC1R6i00EFGpcfHhZHIxxOcOffMnZBdv2wxRDUw9Xghc8LzQSHEZqwkSn0NEx2u4G2w04GynOIRXINUPNhAaBFWIl%2bSqX3JjSZGB796vXfzX%2f0svF50BN9wdNce8g9JAmLTsrbwQ1nEllC5aX6Jmxcp4ShS80KuXzJHsDN9emuM8AAAA%3d

DiagnosticRole | where PreciseTimeStamp >= datetime(2017-07-27 20:00:31.4319989) and PreciseTimeStamp <= datetime(2017-07-27 20:10:31.4319989)
| where RequestId in ("g-b5f92ec1-35a6-480f-9a3f-9802f67055f4")

**Comment by hforeste** [comment]
Looks like the start time in the query was 2017-06-28 and according to the georegionservice database the environment did not exist until 2017-06-30 18:32:07 and the first heart beat event occurred around 2017-06-30 23:32:00

**Comment by hforeste** [comment]
For tracking purposes, these are the requestids in the past 14 days with the gm-prod-sn1 issue.

RequestId
g-96b51d57-2a3a-4bc4-b3d8-035045cbf416
g-253003b7-e78d-4db1-b08d-69cd089365fc
g-a64ae1e4-41cc-4282-bc7b-661b0056d874
g-ab9d0100-265e-4885-805e-71e77dbaf029
g-b1f5403b-a7e0-4c68-8725-6e78db9a0e14

**Comment by hforeste** [comment]
I have a fix for this checked in, just needs to be deployed
