### ISSUE TITLE
ASE Vnet Verifier : Internal Server error

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#888]
Detector : VNET Verifier
ASE : z-uki-mach-dv-en1-ase01

Query:
DiagnosticRole 
| where RequestId == "g-9cc9969d-3de3-4294-a114-cfc31e59fb71" 
| project EventId , Source , Exception , ExceptionDetails 

Exception:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Web.Hosting.Diagnostics.Common.GeoMasterClient.<HttpPost>d__7`2.MoveNext()

**Comment by ShekharGupta1988** [comment]
Looks like a bug in vnet verifier API (as per Aleks) where the nsg rules are in different format than expected by vnet verifier.
In a few rules (take a look at “Allow_Outbound_Azure_europewest” as an example), instead of just “destinationAddressPrefix” with a single prefix, this customer has “destinationAddressPrefixes” followed by a large list of  addresses (about 430 of them)

Vnet verifier needs to be fixed for this. 

Closing this issue
