### ISSUE TITLE
ClrProfilingCollector - OpenProcess fails with Access Denied error

### ISSUE THREAD

**Issue by puneetg1983** [ShekharGupta1988/AppLensV2#899]
System.ComponentModel.Win32Exception : Access is denied 
    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at ClrProflingCollector.Program.Main(String[] args)

**Comment by puneetg1983** [comment]
closing this one as I just saw this error once in our logs. will reopen if we see this again
