### ISSUE TITLE
ASYNC stack parsing seems broken in CLR Profiler

### ISSUE THREAD

**Issue by puneetg1983** [ShekharGupta1988/AppLensV2#996]
[2/14/2018 9:52:01 PM] 6f6aa348-2625-4e6f-8a26-e1e2a273472a [VERB] Loading symbols
[2/14/2018 9:52:01 PM] 6f6aa348-2625-4e6f-8a26-e1e2a273472a [VERB] Symbol reader _NT_SYMBOL_PATH= {
[2/14/2018 9:52:01 PM] 6f6aa348-2625-4e6f-8a26-e1e2a273472a [VERB]     D:\local\Temp\Logs\daastest\18-02-14\RD00155DF647C7\CLRProfilingCollector\180214_2149202113\180214_2151202113;
[2/14/2018 9:52:01 PM] 6f6aa348-2625-4e6f-8a26-e1e2a273472a [VERB]     SRV*D:\home\data\DaaS\symbols*http://msdl.microsoft.com/download/symbols;
[2/14/2018 9:52:38 PM] 6f6aa348-2625-4e6f-8a26-e1e2a273472a [VERB] Generating stack-traces for slow requests
    Error: Array is variable sized and does not follow  prefix convention.
    Error: Array is variable sized and does not follow  prefix convention.
[2/14/2018 9:52:43 PM] 6f6aa348-2625-4e6f-8a26-e1e2a273472a [ERR] Failed while generating ASYNC stacks System.ApplicationException : Could not resolve symbols for Task library (mscorlib), task stacks will not work. 
    at Microsoft.Diagnostics.Tracing.ActivityComputer.ResolveWellKnownSymbols()
   at Microsoft.Diagnostics.Tracing.ActivityComputer.TrimETWFrames(CallStackIndex callStackIndex)
   at Microsoft.Diagnostics.Tracing.ActivityComputer.GetCallStackWithActivityFrames(CallStackIndex baseStack, TraceActivity activity, Func`2 topFrames)
   at Microsoft.Diagnostics.Tracing.ActivityComputer.GetCallStack(MutableTraceEventStackSource outputStackSource, TraceEvent data, Func`2 topFrames, Boolean trimEtwFrames)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GetCallStack(TraceEvent data, TraceThread thread)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.<GenerateThreadTimeStacks>b__7_10(TraceEvent data)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventData.Dispatch()
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.DoDispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLogEventSource.Process()
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateThreadTimeStacks(MutableTraceEventStackSource outputStackSource, TraceEvents traceEvents)
   at ClrProfilingAnalyzer.Program.GenerateStackTracesForSlowRequests(SymbolReader symbolReader, TraceLog dataFile, Dictionary`2 iisRequests, ClrProfilingAnalyzerStats stats)

**Comment by puneetg1983** [comment]
Fow now, I have put the PDB's for ngen'ed images directly in the DAAS package. I will also work in parallel to get them added to the Antares Image too.
